#!/usr/bin/env bash

if [ "$#" -gt 0 ]
then 
    if [ "$1" = "clean" ]
    then
      echo -e "\e[1;34m#\e[0m"
      echo -e "\e[1;34m# Start cleaning directory.\e[0m"
      echo -e "\e[1;34m#\e[0m"
      echo "rm -f *.log"
      rm -f *.log
      echo "rm -f *.toc"
      rm -f *.toc
      echo "rm -f *.out"
      rm -f *.out
      echo "rm -f *.aux"
      rm -f *.aux
      echo -e "\e[1;34m#\e[0m"
      echo -e "\e[1;34m# End cleaning directory.\e[0m"
      echo -e "\e[1;34m#\e[0m"
    fi
else
  echo -e "\e[1;34m#\e[0m"
  echo -e "\e[1;34m# Started generating document.\e[0m"
  echo -e "\e[1;34m#\e[0m"
  pdflatex -interaction=nonstopmode main.tex | grep !
  echo -e "\e[1;34m#\e[0m"
  echo -e "\e[1;34m# End generating document .\e[0m"
  echo -e "\e[1;34m#\e[0m"
fi

