#!/usr/bin/env bash

if [ "$#" -gt 0 ]
then 
    if [ "$1" = "clean" ]
    then
      echo -e "\e[1;34m#\e[0m"
      echo -e "\e[1;34m# Start cleaning directory.\e[0m"
      echo -e "\e[1;34m#\e[0m"
      echo "rm -f *.log"
      rm -f *.log
      echo "rm -f *.toc"
      rm -f *.toc
      echo "rm -f *.out"
      rm -f *.out
      echo "rm -f *.aux"
      rm -f *.aux
      echo -e "\e[1;34m#\e[0m"
      echo -e "\e[1;34m# End cleaning directory.\e[0m"
      echo -e "\e[1;34m#\e[0m"
    fi
else
  tput setaf 4
  echo "#"
  echo "# Started generating document."
  echo "#"
  tput setaf 1 
  pdflatex -interaction=nonstopmode main.tex | grep !
  tput setaf 4
  echo "#"
  echo "# End generating document."
  echo "#"
  tput sgr0
fi

