#!/usr/bin/env bash

if [ "$#" -gt 0 ]
then 
    if [ "$1" = "clean" ]
    then
      tput setaf 4
      echo  "#"
      echo  "# Started cleaning directory."
      echo  "#"
      tput setaf 1 
      echo "rm -f *.log"
      rm -f *.log
      echo "rm -f *.toc"
      rm -f *.toc
      echo "rm -f *.out"
      rm -f *.out
      echo "rm -f *.aux"
      rm -f *.aux
      echo "rm -f *.pdf"
      rm -f *.pdf
      echo "rm -f *.lof"
      rm -f *.lof
      tput setaf 4
      echo "#"
      echo "# Ended cleaning directory."
      echo "#"
      tput sgr0
    fi
else
  tput setaf 4
  echo "#"
  echo "# Started generating document."
  echo "#"
  tput setaf 1 
  pdflatex -interaction=nonstopmode main.tex | grep !
  tput setaf 4
  echo "#"
  echo "# Ended generating document."
  echo "#"
  tput sgr0
fi

